---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rabbitmq]
      - recipe[rabbitmq_federation]
  - name: upstream
    driver:
      instance_name: upstream
    run_list:
      - recipe[sensu::rabbitmq]
      - recipe[sensu]
  - name: sensu
    driver:
      links: "upstream:upstream"
    run_list:
      - recipe[sensu::rabbitmq]
      - recipe[sensu]
      - recipe[rabbitmq_federation::sensu]
